name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
env:
  APP_NAME: contoso97aca
  RESOURCE_GROUP: contoso97rg
  ENV_NAME: contoso97acaenv
  IMAGE: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          appName: ${{ env.APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppEnvironment: ${{ env.ENV_NAME }}
          imageToDeploy: ${{ env.IMAGE }}
